// <auto-generated />
namespace PetterService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StoreGallery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreGallery));
        
        string IMigrationMetadata.Id
        {
            get { return "201509210603390_StoreGallery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
